---
name: Trigger downstream workflow

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

env:
  DOWNSTREAM_REPO: nixos-config
  WORKFLOW_BRANCH: master
  WORKFLOW_FILE: sync-upstream.yml
  REF: ${{ github.head_ref || github.ref_name }} 

jobs:
  dispatch-downstream-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub auth token
        # https://github.com/tibdex/github-app-token
        id: generate_token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Trigger
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ env.DOWNSTREAM_REPO }}
          github_token: ${{ steps.generate_token.outputs.token }}
          workflow_file_name: ${{ env.WORKFLOW_FILE }}
          ref: ${{ env.WORKFLOW_BRANCH }}
          client_payload: '{"target":"dotfiles"}'
          trigger_workflow: true
          propagate_failure: false
          wait_workflow: false
