---
name: Synchronize upstream inputs

on:
  workflow_dispatch:
    inputs:
      target:
        type: string
        description: flake input to be synced
        required: true
      branch:
        type: string
        description: upstream branch to be synced
        required: false

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub auth token
        # https://github.com/tibdex/github-app-token
        id: generate_token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          
      - uses: actions/checkout@main
        with:
        #   ref: master
        #   submodules: true
          token: ${{ steps.generate_token.outputs.token }}

      - name: Determine flake input
        id: flake_input
        shell: bash
        run: |
          if [ "${{ inputs.branch }}" = "x1-carbon" ]; then
            echo "INPUT=${{ inputs.target }}-laptop" >> $GITHUB_OUTPUT
          else
            echo "INPUT=${{ inputs.target }}-universal" >> $GITHUB_OUTPUT
          fi

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - name: update flake upstream input
        shell: bash
        run: |
          nix flake lock --update-input "${{ steps.flake_input.outputs.INPUT }}"

      - uses: EndBug/add-and-commit@main
        with:
          add: flake.lock
          commit: --signoff
          message: "chore(flake): update flake.lock to sync input.${{ inputs.target }}"
